server:
  port: 8084

spring:
  application:
    name: time-service
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    table: flyway_time_history
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Default Datasource
spring.datasource:
  url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}

tenant:
  service:
    url: ${SERVICE_TENANT_URL}
