server:
  port: 8083

spring:
  application:
    name: project-service
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    table: flyway_project_history
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Default Datasource (will be overridden by dynamic routing)
spring.datasource:
  url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}

tenant:
  service:
    url: ${SERVICE_TENANT_URL}
